name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: yaml
          coverage: xdebug
          tools: pecl, composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Build
        run: php build.php

      - name: Create archive
        run: zip -r out.zip out/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: out.zip
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve artifact ID
        id: artifact
        run: |
          ARTIFACT_ID=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts \
            | jq '.artifacts[] | select(.name=="out") | .id')

          echo "id=$ARTIFACT_ID" >> $GITHUB_OUTPUT

      - name: Notify deployment server
        run: |
          curl -X POST https://archbar.me/deploy.php \
            -F "repo=${{ github.repository }}" \
            -F "artifact_id=${{ steps.artifact.outputs.id }}"
